const ActionTypes = {
    REQUEST_REPOSITORIES: "REQUEST_REPOSITORIES",
    RECEIVE_REPOSITORIES: "RECEIVE_REPOSITORIES",

    ON_STATUS_UPDATE: "ON_STATUS_UPDATE",
    ON_SOCKET_CLOSED: "ON_SOCKET_CLOSED"
};

export default ActionTypes;