const ActionTypes = {
    REQUEST_REPOSITORIES: "REQUEST_REPOSITORIES",
    RECEIVE_REPOSITORIES: "RECEIVE_REPOSITORIES",
    RECEIVE_NEW_REPOSITORY_VALIDATION_RESULTS: "RECEIVE_NEW_REPOSITORY_VALIDATION_RESULTS",
    ON_SAVE_REPOSITORY: "ON_SAVE_REPOSITORY",

    RECEIVE_RECORD_STATUS: "RECEIVE_RECORD_STATUS",
    RECEIVE_ERROR_STATUS: "RECEIVE_ERROR_STATUS",
    RECEIVE_STATUS_CODES: "RECEIVE_STATUS_CODES",

    ON_STATUS_UPDATE: "ON_STATUS_UPDATE",
    ON_SOCKET_CLOSED: "ON_SOCKET_CLOSED",

    ON_FETCHER_RUNSTATE_CHANGE: "ON_FETCHER_RUNSTATE_CHANGE"
};

export default ActionTypes;