const ActionTypes = {
    RECEIVE_REPOSITORIES: "RECEIVE_REPOSITORIES",
    ON_REPOSITORY_STATUS_UPDATE: "ON_REPOSITORY_STATUS_UPDATE",
    RECEIVE_REPOSITORY: "RECEIVE_REPOSITORY",
    RECEIVE_REPOSITORY_VALIDATION_RESULTS: "RECEIVE_REPOSITORY_VALIDATION_RESULTS",
    RECEIVE_NEW_REPOSITORY_VALIDATION_RESULTS: "RECEIVE_NEW_REPOSITORY_VALIDATION_RESULTS",
};

export default ActionTypes;