DROP TABLE IF EXISTS DARE_PREPROCES;

CREATE TABLE DARE_PREPROCES (
  ID NUMBER(10) AUTO_INCREMENT,
  STATE NUMBER(10) DEFAULT 0 NOT NULL,
  KBOBJID VARCHAR2(255) NOT NULL,
  TS_CREATE TIMESTAMP(6) NOT NULL,
  TS_PROCESSED TIMESTAMP(6) DEFAULT NULL,
  FINGERPRINT VARCHAR2(512) DEFAULT NULL,
  REPOSITORY_ID NUMBER(10) NOT NULL,
  OAI_ID VARCHAR2(255) NOT NULL,
  OAI_DATESTAMP VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID)
);
