DROP TABLE IF EXISTS ERROR_REPORTS;

CREATE TABLE ERROR_REPORTS (
  DARE_PREPROCES_ID NUMBER(10),
  MESSAGE varchar2(1024) DEFAULT NULL,
  URL varchar2(1024) DEFAULT NULL,
  STACKTRACE clob,
  STATUS_CODE number(10) DEFAULT NULL
);

