BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE ERROR_REPORTS';
  EXCEPTION
  WHEN OTHERS THEN NULL;
END;

CREATE TABLE ERROR_REPORTS (
  DARE_PREPROCES_ID NUMBER(10),
  MESSAGE varchar2(1024) DEFAULT NULL,
  URL varchar2(1024) DEFAULT NULL,
  STACKTRACE clob,
  STATUS_CODE number(10) DEFAULT NULL
)

CREATE INDEX oai_record_error_index ON ERROR_REPORTS (STATUS_CODE)
